- hosts: managers
  tasks:
    - name: copy license file
      copy:
        src: docker_subscription.lic
        dest: /tmp/docker_subscription.lic
      become: yes
      when: inventory_hostname == groups['managers'][0]
    - include_role:
        name: dockeree-ucp-dtr
        tasks_from: ucp
      vars:
        #docker_ucp_fqdn_san: --san ucp.devops.mycompany.com
        docker_external_cert: --external-server-cert
      when: inventory_hostname == groups['managers'][0]      
