apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
spec:
  tls:
  - hosts:
    - cafe.apps.vijuto.com
    secretName: cafe-secret
  - hosts:
    - tea.apps.vijuto.com
    secretName: cafe-secret
  rules:
  - host: tea.apps.vijuto.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tea-svc
          servicePort: 80
  - host: cafe.apps.vijuto.com
    http:
      paths:
      - path: /
        backend:
          serviceName: coffee-svc
          servicePort: 80
